substitutions:
  system_name: d1_mini_esphome_plant_soil_moisture
  friendly_name: D1 Mini Plant Soil Moisture

logger:
  level: DEBUG

ota:

mqtt:
  broker: 192.168.1.50
  discovery: True
  birth_message:
  will_message:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: HIGH
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.125
    gateway: 192.168.1.1
    subnet: 255.255.255.0

deep_sleep:
  sleep_duration: 12h
  run_duration: 10s
  id: deep_sleep_1

esphome:
  name: ${system_name}
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: -500
    then:
      - logger.log: Waiting for WiFi!
      - wait_until:
          wifi.connected:
      - logger.log: WiFi is connected!
      - script.execute: plantScript
      - script.execute: bme280Script
      - script.execute: wifi_signal_strengthScript
      - logger.log: Waiting 1s..!
      - delay: 2s
      - logger.log: Going to sleep!
      - deep_sleep.enter: deep_sleep_1

script:
  - id: plantScript
    then:
      - logger.log: "plantScript: start"
      - switch.turn_on: plantPower
      - delay: 100ms
      - component.update: plantSensor
      - delay: 25ms
      - switch.turn_off: plantPower
      - logger.log: "plantScript: done"

  - id: bme280Script
    then:
      - logger.log: "bme280Script: start"
      - component.update: bme280Sensor
      - delay: 25ms
      - logger.log: "bme280Script: done"
      
  - id: wifi_signal_strengthScript
    then:
      - logger.log: "bme280Script: start"
      - component.update: wifi_signal_strength
      - logger.log: "bme280Script: done"

switch:
  - platform: gpio
    pin: D5
    id: plantPower
    restore_mode: RESTORE_DEFAULT_OFF
    internal: true
    
  - platform: gpio
    pin: D3
    id: bmePower
    restore_mode: RESTORE_DEFAULT_ON
    internal: true
    
output:
 - platform: gpio
   id: built_in_led_and_bme_power
   pin:
      number: D4
      mode: INPUT_PULLUP
      inverted: true

i2c:
  sda: D2
  scl: D1
  scan: False
  id: i2c_bme

text_sensor:
  - platform: version
    name: "${system_name}_version"

sensor:
  - platform: wifi_signal
    id: wifi_signal_strength
    name: "${system_name}_wifi_signal"
    update_interval: never
    
  - platform: bme280
    id: bme280Sensor
    i2c_id: i2c_bme
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: never
    
  - platform: adc
    id: plantSensor
    update_interval: never
    pin: A0
    name: "Soil Moisture"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    retain: True
    filters:
      - calibrate_linear:
          - 1.0 -> 0.0
          - 0.0 -> 100.0
